---
- name: remove metrics components
  command: >
    {{ openshift.common.client_binary }} -n '{{ project }}'
    delete --selector=metrics-infra
    svc,replicationcontrollers,serviceaccounts,secrets,templates,routes,pvc
  register: ret
  changed_when: "ret.stdout != 'No resources found'"
- name: test cluster-reader permissions for the heapster service account
  command: >
    {{ openshift.common.client_binary }} get clusterrolebindings
    -o jsonpath='{.items[?(@.roleRef.name == "cluster-reader")].userNames}'
  register: ret
  changed_when: false
- name: remove heapster cluster role binding
  command: >
    {{ openshift.common.admin_binary }} policy remove-cluster-role-from-user
    cluster-reader 'system:serviceaccount:{{ project }}:heapster'
  when: "'system:serviceaccount:{{ project }}:heapster' in ret.stdout"
- name: test view permissions for the hawkular service account
  command: >
    {{ openshift.common.client_binary }} get rolebindings
    -o jsonpath='{.items[?(@.roleRef.name == "view")].userNames}'
  register: ret
  changed_when: false
- name: remove hawkular role binding
  command: >
    {{ openshift.common.admin_binary }} policy remove-role-from-user
    view hawkular
  when: "'system:serviceaccount:{{ project }}:hawkular' in ret.stdout"
