---
- name: generate heapster key/cert
  command: >
    {{ openshift.common.admin_binary }} ca create-server-cert
    --key='{{ openshift_metrics_certs_dir }}/heapster.key'
    --cert='{{ openshift_metrics_certs_dir }}/heapster.cert'
    --hostnames=heapster
    --signer-cert='{{ openshift_metrics_certs_dir }}/ca.crt'
    --signer-key='{{ openshift_metrics_certs_dir }}/ca.key'
    --signer-serial='{{ openshift_metrics_certs_dir }}/ca.serial.txt'
# TODO maybe there's an easier way to get the service accounts' ca crt?
- name: get heapster service account secrets
  shell: >
    {{ openshift.common.client_binary }} -n '{{ openshift_metrics_project }}'
    get serviceaccount/default
    --template '{{ '{{range .secrets}}{{println .name}}{{end}}' }}'
    | grep ^default-token-
  register: sa_secret
- name: get heapster service account ca
  command: >
    {{ openshift.common.client_binary }} -n '{{ openshift_metrics_project }}'
    get 'secret/{{ sa_secret.stdout }}'
    --template '{{ '{{index .data "ca.crt"}}' }}'
  register: sa_secret
- name: read files for the heapster secret
  command: >
    base64 --wrap 0 '{{ openshift_metrics_certs_dir }}/heapster.{{ item }}'
  register: heapster_secret
  with_items:
  - cert
  - key
- name: generate heapster secret template
  template:
    src: secret.j2
    dest: "{{ mktemp.stdout }}/templates/heapster_secrets.yaml"
  vars:
    name: heapster-secrets
    labels:
      metrics-infra: heapster
    data:
      heapster.cert: "{{ heapster_secret.results[0].stdout }}"
      heapster.key: "{{ heapster_secret.results[1].stdout }}"
      heapster.client-ca: "{{ sa_secret.stdout }}"
      heapster.allowed-users: "{{ openshift_metrics_heapster_allowed_users|b64encode }}"
