---
- name: Generating serviceaccounts
  template: src={{template_dir}}/serviceaccount.j2 dest={{mktemp.stdout}}/templates/metrics-{{component}}-sa.yaml
  vars:
    obj_name: "{{component}}"
    labels:
      metrics-infra: support
    secrets:
    - hawkular-{{component}}-secrets
  with_items:
    - hawkular
    - cassandra
  loop_control:
    loop_var: component

- name: Generating serviceaccount for heapster
  template: src={{template_dir}}/serviceaccount.j2 dest={{mktemp.stdout}}/templates/metrics-{{obj_name}}-sa.yaml
  vars:
    obj_name: heapster
    labels:
      metrics-infra: support
    secrets:
    - heapster-secrets
    - hawkular-metrics-certificate
    - hawkular-metrics-account
