---
- name: Generating serviceaccounts
  template: src={{template_dir}}/serviceaccount.j2 dest={{mktemp.stdout}}/templates/metrics-{{item}}-sa.yaml
  vars:
    obj_name: "{{item}}"
    labels:
      metrics-infra: support
    secrets:
    - hawkular-{{item}}-secrets
  with_items:
    - hawkular
    - cassandra

- name: Generating serviceaccount for heapster
  template: src={{template_dir}}/serviceaccount.j2 dest={{mktemp.stdout}}/templates/metrics-{{obj_name}}-sa.yaml
  vars:
    obj_name: heapster
    labels:
      metrics-infra: support
    secrets:
    - heapster-secrets
    - hawkular-metrics-certificate
    - hawkular-metrics-account
