---
# This is the base configuration for installing the other components
- name: Create temp directory for doing work in
  command: mktemp -td openshift-metrics-ansible-XXXXXX
  register: mktemp
  changed_when: False

- debug: msg="Created temp dir {{mktemp.stdout}}"

- name: Create temp directory for all our templates
  file: path={{mktemp.stdout}}/templates state=directory mode=0755
  changed_when: False

- include: generate_serviceaccounts.yaml
- include: generate_services.yaml
- include: generate_certificates.yaml
- include: generate_rolebindings.yaml
