---
- name: generate replication controller templates
  template:
    src: "{{ item }}.j2"
    dest: "{{ mktemp.stdout }}/templates/{{ item }}.yaml"
  with_items:
  - hawkular_metrics_rc
  - hawkular_cassandra_rc
- name: create hawkular metrics objects
  command: >
    {{ openshift.common.client_binary }} -n '{{ project }}'
    create -f '{{ mktemp.stdout }}/templates/{{ item }}'
  with_items:
  - hawkular_metrics_secrets.yaml
  - hawkular_metrics_certificate.yaml
  - hawkular_metrics_account.yaml
  - cassandra_secrets.yaml
  - cassandra_certificate.yaml
  - metrics-hawkular-sa.yaml
  - metrics-hawkular-metrics-svc.yaml
  - hawkular_metrics_rc.yaml
  - metrics-hawkular-cassandra-svc.yaml
  - metrics-hawkular-cassandra-nodes-svc.yaml
  - metrics-cassandra-sa.yaml
- name: process cassandra template
  shell: >
    {{ openshift.common.client_binary }} -n '{{ project }}'
    process -f '{{ mktemp.stdout }}/templates/hawkular_cassandra_rc.yaml'
    --value 'NODE={{ item }}'
    {% if item == '1' %}--value MASTER=true{% endif %}
    | oc create -f -
  with_sequence: start=1 end={{ hawkular_cassandra_nodes }}
- name: create the hawkular-metrics route
  command: >
    {{ openshift.common.client_binary }} -n '{{ project }}'
    create route reencrypt hawkular-metrics
    --hostname='{{ hawkular_metrics_hostname }}'
    --service=hawkular-metrics
    --dest-ca-cert='{{ mktemp.stdout }}/certs/ca.crt'
