---
- name: Generate hawkular replication controller
  #template: src=hawkular.j2 dest={{mktemp.stdout}}/templates/metrics-hawkular-rc.yaml
  template: src=hawkular.j2 dest={{out_dir}}/templates/metrics-hawkular-rc.yaml
# TODO import templates to this repo?
- name: create templates
  command: >
    {{ openshift.common.client_binary }} -n '{{ project }}'
    create -f '{{ origin_metrics_dir }}/deployer/templates/{{ item }}.yaml'
  with_items:
  - hawkular-metrics
  - hawkular-cassandra
  - hawkular-cassandra-node-pv
  - hawkular-cassandra-node-dynamic-pv
  - hawkular-cassandra-node-emptydir
  - support
- name: create hawkular metrics objects
  command: >
    {{ openshift.common.client_binary }} -n '{{ project }}'
    create -f '{{ mktemp.stdout }}/templates/{{ item }}'
  with_items:
  - hawkular_metrics_secrets.yaml
  - hawkular_metrics_certificate.yaml
  - hawkular_metrics_account.yaml
  - cassandra_secrets.yaml
  - cassandra_certificate.yaml
- name: process other templates
  shell: >
    {{ openshift.common.client_binary }} -n '{{ project }}'
    process '{{ item }}'
    | oc create -f -
  with_items:
  - hawkular-cassandra-services
  - hawkular-support
# TODO persistent storage
- name: process hawkular-metrics template
  shell: >
    {{ openshift.common.client_binary }} -n '{{ project }}'
    process hawkular-metrics
    --value 'IMAGE_PREFIX={{ image_prefix }}'
    --value 'IMAGE_VERSION={{ image_version }}'
    --value 'METRIC_DURATION={{ metrics_duration }}'
    --value 'MASTER_URL={{ master_url }}'
    --value 'USER_WRITE_ACCESS={{ hawkular_user_write_access }}'
    --value 'USE_PERSISTENT_STORAGE=false'
    | oc create -f -
- name: process cassandra template for the master node
  shell: >
    {{ openshift.common.client_binary }} -n '{{ project }}'
    process hawkular-cassandra-node-emptydir
    --value 'IMAGE_PREFIX={{ image_prefix }}'
    --value 'IMAGE_VERSION={{ image_version }}'
    --value NODE=1
    --value MASTER=true
    | oc create -f -
## TODO multi-node cassandra
#- name: process cassandra template for other nodes
#  shell: >
#    {{ openshift.common.client_binary }} -n '{{ project }}'
#    process hawkular-cassandra-node-emptydir
#    --value 'IMAGE_PREFIX={{ image_prefix }}'
#    --value 'IMAGE_VERSION={{ image_version }}'
#    --value NODE={{ item }}
#    | oc create -f -
#  with_sequence: start=1 end={{ cassandra_nodes }}
#  when: {{ cassandra_nodes > 1 }}
- name: create the hawkular-metrics route
  command: >
    {{ openshift.common.client_binary }} -n '{{ project }}'
    create route reencrypt hawkular-metrics
    --hostname='{{ hawkular_metrics_hostname }}'
    --service=hawkular-metrics
    --dest-ca-cert='{{ mktemp.stdout }}/certs/ca.crt'
