---
- name: Generate heapster replication controller
  template: src=heapster.j2 dest={{mktemp.stdout}}/templates/metrics-heapster-rc.yaml
- name: test cluster-reader permissions for the heapster service account
  command: >
    {{ openshift.common.client_binary }} get clusterrolebindings
    -o jsonpath='{.items[?(@.roleRef.name == "cluster-reader")].userNames}'
  register: clusterreader_rolebindings
  changed_when: false
- name: add the cluster-reader role to the heapster service account
  command: >
    '{{ openshift.common.admin_binary }}' policy
    -n '{{ project }}' add-cluster-role-to-user
    cluster-reader 'system:serviceaccount:{{ project }}:heapster'
  when: >
    'system:serviceaccount:{{ project }}:heapster'
    not in clusterreader_rolebindings.stdout
- name: create heapster objects
  command: >
    {{ openshift.common.client_binary }} -n '{{ project }}'
    create -f '{{ mktemp.stdout }}/templates/{{ item }}'
  with_items:
  - heapster_secrets.yaml
  - metrics-heapster-sa.yaml
  - metrics-heapster-svc.yaml
  - metrics-heapster-rc.yaml
