---
# This is the base configuration for installing the other components
- name: Create temp directory for doing work in
  command: mktemp -d /tmp/openshift-metrics-ansible-XXXXXX
  register: mktemp
  changed_when: False

- debug: msg="Created temp dir {{mktemp.stdout}}"

- name: copy `templates` directory
  copy:
    src: "{{ role_path }}/files/templates/"
    dest: "{{ mktemp.stdout }}/templates"

- include: generate_serviceaccounts.yaml
- include: generate_services.yaml
- include: generate_certificates.yaml
