---
- name: Install Metrics
  include: "{{ role_path }}/tasks/install_{{ item }}.yaml"
  vars:
    template_dir: ../openshift_logging/templates
    out_dir: /home/vagrant
  with_items:
    - metrics
    - heapster
