---
- name: stop logging
  include: stop_cluster.yaml

# delete the deployment objects that we had created
- name: delete logging api objects
  command: >
    {{ openshift.common.client_binary }} --config={{ mktemp.stdout }}/admin.kubeconfig
    delete {{ item }} --selector logging-infra -n {{ logging_namespace }}
  with_items:
    - dc
    - rc
    - svc
    - routes
    - templates
    - daemonset
  ignore_errors: yes

# delete the oauthclient
- name: delete oauthclient kibana-proxy
  command: >
    {{ openshift.common.client_binary }} --config={{ mktemp.stdout }}/admin.kubeconfig delete oauthclient kibana-proxy
  ignore_errors: yes

# delete any image streams that we may have created
- name: delete logging is
  command: >
    {{ openshift.common.client_binary }} --config={{ mktemp.stdout }}/admin.kubeconfig
    delete is -l logging-infra=support -n {{ logging_namespace }}
  ignore_errors: yes

# delete our old secrets
- name: delete logging secrets
  command: >
    {{ openshift.common.client_binary }} --config={{ mktemp.stdout }}/admin.kubeconfig
    delete secret {{ item }} -n {{ logging_namespace }}
  with_items:
    - logging-fluentd
    - logging-elasticsearch
    - logging-kibana
    - logging-kibana-proxy
    - logging-curator
  ignore_errors: yes

# delete role bindings -- may not be necessary?
- name: delete rolebindings
  command: >
    {{ openshift.common.client_binary }} --config={{ mktemp.stdout }}/admin.kubeconfig
    delete rolebinding {{ item }} -n {{ logging_namespace }}
  with_items:
    - logging-elasticsearch-view-role
  ignore_errors: yes

# delete our service accounts
- name: delete service accounts
  command: >
    {{ openshift.common.client_binary }} --config={{ mktemp.stdout }}/admin.kubeconfig
    delete serviceaccount {{ item }} -n {{ logging_namespace }}
  with_items:
    - aggregated-logging-elasticsearch
    - aggregated-logging-kibana
    - aggregated-logging-curator
    - aggregated-logging-fluentd
  ignore_errors: yes

# delete our roles
- name: delete roles
  command: >
    {{ openshift.common.client_binary }} --config={{ mktemp.stdout }}/admin.kubeconfig
    delete clusterrole {{ item }} -n {{ logging_namespace }}
  with_items:
    - daemonset-admin
  ignore_errors: yes
