---
- name: Generating secrets for logging components
  template: src=secret.j2 dest={{mktemp.stdout}}/templates/{{secret_name}}-secret.yaml
  vars:
    secret_name: logging-{{component}}
    secrets: [{key: ca, value: "{{lookup('file', '{{mktemp.stdout}}/ca.crt')}}"},{key: key, value: "{{lookup('file', '{{mktemp.stdout}}/system.logging.{{component}}.key')}}"},{key: cert, value: "{{lookup('file', '{{mktemp.stdout}}/system.logging.{{component}}.crt')}}"}]
  with_items:
    - kibana
    - curator
    - fluentd
  loop_control:
    loop_var: component

- name: Generating secrets for kibana proxy
  template: src=secret.j2 dest={{mktemp.stdout}}/templates/{{secret_name}}-secret.yaml
  vars:
    secret_name: logging-kibana-proxy
    secrets: [{key: oauth-secret, value: "{{oauth_secret.stdout}}"},{key: session-secret, value: "{{session_secret.stdout}}"},{key: server-key, value: "{{lookup('file', '{{mktemp.stdout}}/kibana-internal.key')}}"},{key: server-cert, value: "{{lookup('file', '{{mktemp.stdout}}/kibana-internal.crt')}}"},{key: server-tls, value: "{{lookup('file', '{{mktemp.stdout}}/server-tls.json')}}"}]

- name: Generating secrets for elasticsearch
  command: "{{openshift.common.client_binary}} --config={{ mktemp.stdout }}/admin.kubeconfig secrets new logging-elasticsearch key={{mktemp.stdout}}/logging-es.key truststore={{mktemp.stdout}}/logging-es.pkcs12 searchguard.key={{mktemp.stdout}}/elasticsearch.key searchguard.truststore={{mktemp.stdout}}/elasticsearch.pkcs12 admin-key={{mktemp.stdout}}/system.admin.key admin-cert={{mktemp.stdout}}/system.admin.crt admin-ca={{mktemp.stdout}}/ca.crt admin.jks={{mktemp.stdout}}/system.admin.pkcs12 -o yaml"
  register: logging_es_secret

- copy: content="{{logging_es_secret.stdout}}" dest={{mktemp.stdout}}/templates/logging-elasticsearch-secret.yaml
  when: logging_es_secret.stdout is defined
