---
- debug: msg="certs are {{chain_certs}} and oid is {{oid}}"
  when: chain_certs is defined and oid is defined

- debug: msg="certs are {{chain_certs}}"
  when: chain_certs is defined and oid is undefined

- name: Build extensions with certs
  shell: echo "{{chain_certs}}{{ (oid) | ternary(',oid:1.2.3.4.5.5','') }}"
  register: cert_ext
  when: chain_certs is defined and oid is defined

- debug: msg="extensions are {{cert_ext.stdout}}"
  when: cert_ext.stdout is defined

- shell: >
    echo {{ (cert_ext.stdout is defined) | ternary( '-ext san=dns:localhost,ip:127.0.0.1','') }}{{ (cert_ext.stdout is defined) | ternary( cert_ext.stdout, '') }}
  register: extensions

- local_action: stat path="{{mktemp.stdout}}/{{component}}.jks"
  register: jks_file
  become: no

- local_action: stat path="{{mktemp.stdout}}/truststore.jks"
  register: jks_truststore
  become: no

- block:
    - shell: >
        keytool -genkey -alias {{component}} -keystore {{mktemp.stdout}}/{{component}}.jks -keypass kspass -storepass kspass -keyalg RSA -keysize 2048 -validity 712 -dname "CN={{component}}, OU=OpenShift, O=Logging" {{extensions.stdout}}

    - shell: >
        keytool -certreq -alias {{component}} -keystore {{mktemp.stdout}}/{{component}}.jks -storepass kspass -file {{mktemp.stdout}}/{{component}}.csr -keyalg RSA -dname "CN={{component}}, OU=OpenShift, O=Logging" {{extensions.stdout}}

    - shell: >
        openssl ca -in {{mktemp.stdout}}/{{component}}.csr -notext -out {{mktemp.stdout}}/{{component}}.crt -config {{mktemp.stdout}}/signing.conf -extensions v3_req -batch -extensions server_ext

    - shell: >
        keytool -import -file {{mktemp.stdout}}/ca.crt -keystore {{mktemp.stdout}}/{{component}}.jks -storepass kspass -noprompt -alias sig-ca

    - shell: >
         keytool -import -file {{mktemp.stdout}}/{{component}}.crt -keystore {{mktemp.stdout}}/{{component}}.jks -storepass kspass -noprompt -alias {{component}}

  when: not jks_file.stat.exists

- block:
    - shell: >
        keytool -import -file {{mktemp.stdout}}/ca.crt -keystore {{mktemp.stdout}}/truststore.jks -storepass tspass -noprompt -alias sig-ca
  when: not jks_truststore.stat.exists
