---
- name: Generate RoleBindings
  template: src=rolebinding.j2 dest={{mktemp.stdout}}/templates/logging-{{obj_name}}-rolebinding.yaml
  vars:
    obj_name: logging-elasticsearch-view-role
    roleRef:
      kind: ClusterRole
      name: view
    subjects:
      - kind: ServiceAccount
        name: aggregated-logging-elasticsearch
