---
- name: Generating PersistentVolumeClaims
  template: src=pvc.j2 dest={{mktemp.stdout}}/logging-{{pvc_name}}-pvc.yaml
  vars:
    pvc_name: replaceme
    pvc_size: 100G
    pvc_access_modes:
      - ReadWriteOnce
  when: es_pvc_dynamic == False

- name: Generating PersistentVolumeClaims - Dynamic
  template: src=pvc.j2 dest={{mktemp.stdout}}/logging-{{pvc_name}}-pvc.yaml
  vars:
    pvc_name: replaceme-also
    pvc_annotations:
      volume.alpha.kubernetes.io/storage-class: "dynamic"
    pvc_size: 100G
    pvc_access_modes:
      - ReadWriteOnce
  when: es_pvc_dynamic
