---
- name: Generating PersistentVolumeClaims
  template: src=pvc.j2 dest={{mktemp.stdout}}/templates/logging-{{obj_name}}-pvc.yaml
  vars:
    obj_name: replaceme
    size: 100G
    access_modes:
      - ReadWriteOnce
  when: not es_pvc_dynamic

- name: Generating PersistentVolumeClaims - Dynamic
  template: src=pvc.j2 dest={{mktemp.stdout}}/templates/logging-{{obj_name}}-pvc.yaml
  vars:
    obj_name: replaceme-also
    annotations:
      volume.alpha.kubernetes.io/storage-class: "dynamic"
    size: 100G
    access_modes:
      - ReadWriteOnce
  when: es_pvc_dynamic
