---
- block:
    - copy:
        src: elasticsearch-logging.yml
        dest: "{{mktemp.stdout}}/elasticsearch-logging.yml"

    - copy:
        src: elasticsearch.yml
        dest: "{{mktemp.stdout}}/elasticsearch.yml"

    - shell: >
        {{ openshift.common.client_binary }} --config={{ mktemp.stdout }}/admin.kubeconfig create configmap logging-elasticsearch --from-file=logging.yml={{mktemp.stdout}}/elasticsearch-logging.yml --from-file=elasticsearch.yml={{mktemp.stdout}}/elasticsearch.yml -o yaml --dry-run
      register: es_configmap

    - copy:
        content: "{{es_configmap.stdout}}"
        dest: "{{mktemp.stdout}}/templates/logging-elasticsearch-configmap.yaml"
      when: es_configmap.stdout is defined
  check_mode: no

- block:
    - copy:
        src: curator.yml
        dest: "{{mktemp.stdout}}/curator.yml"

    - shell: >
        {{ openshift.common.client_binary }} --config={{ mktemp.stdout }}/admin.kubeconfig create configmap logging-curator --from-file=config.yaml={{mktemp.stdout}}/curator.yml -o yaml --dry-run
      register: curator_configmap

    - copy:
        content: "{{curator_configmap.stdout}}"
        dest: "{{mktemp.stdout}}/templates/logging-curator-configmap.yaml"
      when: curator_configmap.stdout is defined
  check_mode: no

- block:
    - copy:
        src: fluent.conf
        dest: "{{mktemp.stdout}}/fluent.conf"

    - copy:
        src: fluentd-throttle-config.yaml
        dest: "{{mktemp.stdout}}/fluentd-throttle-config.yaml"

    - copy:
        src: secure-forward.conf
        dest: "{{mktemp.stdout}}/secure-forward.conf"

    - shell: >
        {{ openshift.common.client_binary }} --config={{ mktemp.stdout }}/admin.kubeconfig create configmap logging-fluentd --from-file=fluent.conf={{mktemp.stdout}}/fluent.conf --from-file=throttle-config.yaml={{mktemp.stdout}}/fluentd-throttle-config.yaml --from-file=secure-forward.conf={{mktemp.stdout}}/secure-forward.conf -o yaml --dry-run
      register: fluentd_configmap

    - copy:
        content: "{{fluentd_configmap.stdout}}"
        dest: "{{mktemp.stdout}}/templates/logging-fluentd-configmap.yaml"
      when: fluentd_configmap.stdout is defined
  check_mode: no
