---
# This is the base configuration for installing the other components
- name: Create temp directory for doing work in
  command: mktemp -d /tmp/openshift-logging-ansible-XXXXXX
  register: mktemp
  changed_when: False

- debug: msg="Created temp dir {{mktemp.stdout}}"

- include: generate_certs.yaml

- name: Create temp directory for all our templates
  file: path={{mktemp.stdout}}/templates state=directory mode=0755
  changed_when: False

#- include: generate_secrets.yaml

#- include: generate_configmaps.yaml

- include: generate_services.yaml
