---
- name: Generate curator deploymentconfig
  template: src=curator.j2 dest={{mktemp.stdout}}/templates/logging-curator-dc.yaml
  vars:
    component: curator
    logging_component: curator
    deploy_name: "logging-{{component}}"
    image: "{{openshift_logging_image_prefix}}logging-curator:{{openshift_logging_image_version}}"
    es_host: logging-es
    es_port: "{{openshift_logging_es_port}}"
    curator_cpu_limit: "{{openshift_logging_curator_cpu_limit }}"
    curator_memory_limit: "{{openshift_logging_curator_memory_limit }}"
  check_mode: no

- name: Generate OPS curator deploymentconfig
  template: src=curator.j2 dest={{mktemp.stdout}}/templates/logging-curator-ops-dc.yaml
  vars:
    component: curator-ops
    logging_component: curator
    deploy_name: "logging-{{component}}"
    image: "{{openshift_logging_image_prefix}}logging-curator:{{openshift_logging_image_version}}"
    es_host: logging-es-ops
    es_port: "{{openshift_logging_es_ops_port}}"
    curator_cpu_limit: "{{openshift_logging_curator_ops_cpu_limit }}"
    curator_memory_limit: "{{openshift_logging_curator_ops_memory_limit }}"
  when: openshift_logging_use_ops
  check_mode: no
