---
- name: Generate kibana deploymentconfig
  template: src=kibana.j2 dest={{mktemp.stdout}}/templates/logging-kibana-dc.yaml
  vars:
    component: kibana
    logging_component: kibana
    deploy_name: "logging-{{component}}"
    image: "{{openshift_logging_image_prefix}}logging-kibana:{{openshift_logging_image_version}}"
    proxy_image: "{{openshift_logging_image_prefix}}logging-auth-proxy:{{openshift_logging_image_version}}"
    es_host: logging-es
    es_port: "{{openshift_logging_es_port}}"
    kibana_cpu_limit: "{{openshift_logging_kibana_cpu_limit }}"
    kibana_memory_limit: "{{openshift_logging_kibana_memory_limit }}"
    kibana_proxy_cpu_limit: "{{openshift_logging_kibana_proxy_cpu_limit }}"
    kibana_proxy_memory_limit: "{{openshift_logging_kibana_proxy_memory_limit }}"
  check_mode: no

- name: Generate OPS kibana deploymentconfig
  template: src=kibana.j2 dest={{mktemp.stdout}}/templates/logging-kibana-ops-dc.yaml
  vars:
    component: kibana-ops
    logging_component: kibana
    deploy_name: "logging-{{component}}"
    image: "{{openshift_logging_image_prefix}}logging-kibana:{{openshift_logging_image_version}}"
    proxy_image: "{{openshift_logging_image_prefix}}logging-auth-proxy:{{openshift_logging_image_version}}"
    es_host: logging-es-ops
    es_port: "{{openshift_logging_es_ops_port}}"
    kibana_cpu_limit: "{{openshift_logging_kibana_ops_cpu_limit }}"
    kibana_memory_limit: "{{openshift_logging_kibana_ops_memory_limit }}"
    kibana_proxy_cpu_limit: "{{openshift_logging_kibana_ops_proxy_cpu_limit }}"
    kibana_proxy_memory_limit: "{{openshift_logging_kibana_ops_proxy_memory_limit }}"
  when: openshift_logging_use_ops
  check_mode: no
