---
- name: Generate kibana deploymentconfig
  template: src=kibana.j2 dest={{mktemp.stdout}}/templates/logging-kibana-dc.yaml
  vars:
    component: kibana
    logging_component: kibana
    deploy_name: "logging-{{component}}"
    image: "{{image_prefix}}logging-kibana:{{image_version}}"
    proxy_image: "{{image_prefix}}logging-auth-proxy:{{image_version}}"

- name: Generate OPS kibana deploymentconfig
  template: src=kibana.j2 dest={{mktemp.stdout}}/templates/logging-kibana-ops-dc.yaml
  vars:
    component: kibana-ops
    logging_component: kibana
    deploy_name: "logging-{{component}}"
    image: "{{image_prefix}}logging-kibana:{{image_version}}"
    proxy_image: "{{image_prefix}}logging-auth-proxy:{{image_version}}"
    es_host: logging-es-ops
  when: logging_use_ops
