---
- name: Generate curator deploymentconfig
  template: src=curator.j2 dest={{mktemp.stdout}}/templates/logging-curator-dc.yaml
  vars:
    component: curator
    logging_component: curator
    deploy_name: "logging-{{component}}"
    image: "{{image_prefix}}logging-curator:{{image_version}}"

- name: Generate OPS curator deploymentconfig
  template: src=curator.j2 dest={{mktemp.stdout}}/templates/logging-curator-ops-dc.yaml
  vars:
    component: curator-ops
    logging_component: curator
    deploy_name: "logging-{{component}}"
    image: "{{image_prefix}}logging-curator:{{image_version}}"
    es_host: logging-es-ops
  when: logging_use_ops
