---
# This is the base configuration for installing the other components
- name: Check for logging project already exists
  command: >
    {{ openshift.common.client_binary }} --config={{ mktemp.stdout }}/admin.kubeconfig get project {{logging_namespace}} --no-headers
  register: logging_project_result
  ignore_errors: True

- name: "Create logging project"
  command: >
    {{ openshift.common.admin_binary }} --config={{ mktemp.stdout }}/admin.kubeconfig new-project {{logging_namespace}}
  when: logging_project_result.stdout.startswith("{{logging_namespace}}") == False

- include: generate_certs.yaml

- name: Create temp directory for all our templates
  file: path={{mktemp.stdout}}/templates state=directory mode=0755
  changed_when: False

- include: generate_secrets.yaml

- include: generate_configmaps.yaml

- include: generate_services.yaml

- name: Generate kibana-proxy oauth client
  template: src=oauth-client.j2 dest={{mktemp.stdout}}/templates/oauth-client.yaml
  vars:
    secret: "{{oauth_secret.stdout}}"
  when: oauth_secret.stdout is defined

- include: generate_clusterroles.yaml

- include: generate_pvcs.yaml

- include: generate_rolebindings.yaml

- include: generate_serviceaccounts.yaml
