---
- name: Gather OpenShift Logging Facts
  openshift_logging_facts:
    oc_bin: "{{openshift.common.client_binary}}"
    admin_kubeconfig: "{{mktemp.stdout}}/admin.kubeconfig"
    logging_namespace: "{{logging_namespace}}"
  tags: logging_facts
  check_mode: no

- name: Validate Elasticsearch cluster size
  fail: msg="The es_cluster_size may not be scaled down more than 1 less (or 0) the number of Elasticsearch nodes already deployed"
  when: "{{openshift_logging_facts.elasticsearch.deploymentconfigs | length - es_cluster_size | abs > 1}}"

- name: Install logging
  include: "{{ role_path }}/tasks/install_{{ install_component }}.yaml"
  when: openshift_hosted_logging_install | default(true) | bool
  with_items:
    - support
    - elasticsearch
    - kibana
    - curator
    - fluentd
  loop_control:
    loop_var: install_component
        
- name: Register API objects from generated templates
  shell: ls -d -1 {{mktemp.stdout}}/templates/* | sort
  register: logging_objects

- name: Creating API objects from generated templates
  command: >
    {{ openshift.common.client_binary }} --config={{ mktemp.stdout }}/admin.kubeconfig apply -f {{file}} -n {{logging_namespace}}
  with_items: "{{logging_objects.stdout_lines}}"
  loop_control:
    loop_var: file
  when: not ansible_check_mode

- name: Printing out objects to create
  debug: msg="{{lookup('file', file)|quote}}"
  with_fileglob:
    - "{{mktemp.stdout}}/templates/*.yaml"
  loop_control:
    loop_var: file
  when: ansible_check_mode

- name: Scaling up cluster
  include: start_cluster.yaml
