---
- shell: >
    echo "{{ (logging_use_ops) | ternary(ops_host, es_host) }}"
  register: fluentd_ops_host
  check_mode: no

- name: Generating Fluentd daemonset
  template: src=fluentd.j2 dest={{mktemp.stdout}}/templates/logging-fluentd.yaml
  vars:
    daemonset_name: logging-fluentd
    daemonset_component: fluentd
    daemonset_container_name: fluentd-elasticsearch
    daemonset_serviceAccount: aggregated-logging-fluentd
    ops_host: "{{ fluentd_ops_host.stdout }}"
  check_mode: no

- name: "Set permissions for fluentd"
  command: >
    {{ openshift.common.admin_binary}} --config={{ mktemp.stdout }}/admin.kubeconfig policy add-scc-to-user privileged system:serviceaccount:{{logging_namespace}}:aggregated-logging-fluentd
  register: fluentd_output
  failed_when: "fluentd_output.rc == 1 and 'exists' not in fluentd_output.stderr"
  check_mode: no

- name: "Set additional permissions for fluentd"
  command: >
    {{ openshift.common.admin_binary}} --config={{ mktemp.stdout }}/admin.kubeconfig policy add-cluster-role-to-user cluster-reader system:serviceaccount:{{logging_namespace}}:aggregated-logging-fluentd
  register: fluentd2_output
  failed_when: "fluentd2_output.rc == 1 and 'exists' not in fluentd2_output.stderr"
  check_mode: no
