---
- name: Create temp directory for doing work in
  command: mktemp -d /tmp/openshift-logging-ansible-XXXXXX
  register: mktemp
  changed_when: False

- debug: msg="Created temp dir {{mktemp.stdout}}"

- name: Copy the admin client config(s)
  command: >
    cp {{ openshift_master_config_dir }}/admin.kubeconfig {{ mktemp.stdout }}/admin.kubeconfig
  changed_when: False

- name: Gather OpenShift Logging Facts
  openshift_logging_facts:
    oc_bin: "{{openshift.common.client_binary}}"
    admin_kubeconfig: "{{mktemp.stdout}}/admin.kubeconfig"
    logging_namespace: logging

- name: Install logging
  include: "{{ role_path }}/tasks/install_{{ item }}.yaml"
  when: openshift_hosted_logging_install | default(true) | bool
  with_items:
    - logging
    - elasticsearch
    - kibana
    - curator
    - fluentd

- name: Creating API objects from generated templates
  command: >
    {{ openshift.common.client_binary }} --config={{ mktemp.stdout }}/admin.kubeconfig apply -f {{file}} -n logging
  with_fileglob:
    - "{{mktemp.stdout}}/templates/*.yaml"
  loop_control:
    loop_var: file

- name: Scaling up cluster
  include: start_cluster.yaml

- name: Delete temp directory
  file:
    name: "{{ mktemp.stdout }}"
    state: absent
  changed_when: False
