---
- shell: >
    echo "{{openshift_logging_fluentd_nodeselector}}" | cut -d':' -f1
  register: openshift_logging_fluentd_nodeselector_key
  check_mode: no

- shell: >
    echo "{{openshift_logging_fluentd_nodeselector}}" | cut -d' ' -f2
  register: openshift_logging_fluentd_nodeselector_value
  check_mode: no

- shell: >
    {{openshift.common.client_binary}} --config={{mktemp.stdout}}/admin.kubeconfig get node -o name | sed "s,^node/,,g"
  register: openshift_logging_fluentd_hosts
  when: "'--all' in openshift_logging_fluentd_hosts"
  check_mode: no

- name: start fluentd
  include: label_node.yaml
  vars:
    host: "{{fluentd_host}}"
    label: "{{openshift_logging_fluentd_nodeselector_key.stdout}}"
    value: "{{openshift_logging_fluentd_nodeselector_value.stdout}}"
  with_items: "{{openshift_logging_fluentd_hosts.stdout_lines}}"
  loop_control:
    loop_var: fluentd_host

- shell: >
    {{openshift.common.client_binary}} --config={{mktemp.stdout}}/admin.kubeconfig get dc -l component=es -o name -n {{openshift_logging_namespace}}
  register: es_dc
  check_mode: no

- name: start elasticsearch
  include: scale.yaml
  vars:
    desired: 1
  with_items: "{{es_dc.stdout_lines}}"
  loop_control:
    loop_var: object

- shell: >
    {{openshift.common.client_binary}} --config={{mktemp.stdout}}/admin.kubeconfig get dc -l component=kibana -o name -n {{openshift_logging_namespace}}
  register: kibana_dc
  check_mode: no

- name: start kibana
  include: scale.yaml
  vars:
    desired: 1
  with_items: "{{kibana_dc.stdout_lines}}"
  loop_control:
    loop_var: object

- shell: >
    {{openshift.common.client_binary}} --config={{mktemp.stdout}}/admin.kubeconfig get dc -l component=curator -o name -n {{openshift_logging_namespace}}
  register: curator_dc
  check_mode: no

- name: start curator
  include: scale.yaml
  vars:
    desired: 1
  with_items: "{{curator_dc.stdout_lines}}"
  loop_control:
    loop_var: object

- shell: >
    {{openshift.common.client_binary}} --config={{mktemp.stdout}}/admin.kubeconfig get dc -l component=es-ops -o name -n {{openshift_logging_namespace}}
  register: es_dc
  check_mode: no

- name: start elasticsearch-ops
  include: scale.yaml
  vars:
    desired: 1
  with_items: "{{es_dc.stdout_lines}}"
  loop_control:
    loop_var: object
  when: openshift_logging_use_ops

- shell: >
    {{openshift.common.client_binary}} --config={{mktemp.stdout}}/admin.kubeconfig get dc -l component=kibana-ops -o name -n {{openshift_logging_namespace}}
  register: kibana_dc
  check_mode: no

- name: start kibana-ops
  include: scale.yaml
  vars:
    desired: 1
  with_items: "{{kibana_dc.stdout_lines}}"
  loop_control:
    loop_var: object
  when: openshift_logging_use_ops

- shell: >
    {{openshift.common.client_binary}} --config={{mktemp.stdout}}/admin.kubeconfig get dc -l component=curator-ops -o name -n {{openshift_logging_namespace}}
  register: curator_dc
  check_mode: no

- name: start curator-ops
  include: scale.yaml
  vars:
    desired: 1
  with_items: "{{curator_dc.stdout_lines}}"
  loop_control:
    loop_var: object
  when: openshift_logging_use_ops
