apiVersion: v1
kind: Service
metadata:
  name: hawkular-cassandra
  labels:
    metrics-infra: hawkular-cassandra
    name: hawkular-cassandra
spec:
  selector:
    type: hawkular-cassandra
  ports:
  - name: cql-port
    port: 9042
    targetPort: cql-port
  - name: thift-port
    port: 9160
    targetPort: thift-port
  - name: tcp-port
    port: 7000
    targetPort: tcp-port
  - name: ssl-port
    port: 7001
    targetPort: ssl-port
